[font]
size = 12.0
normal = {
  family = "Hack Nerd Font Mono"
}

[colors.primary]
background = "#282c34"
foreground = "#ffffff"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "nu"
args = [
  # "--config", "/dev/null", # so nushell only load env.nu
  "--execute", "zellij attach --create alacritty"
]

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [
  { key = "v", mods = "Control", action = "Paste" }
]
